version: "3.8"
 
services:
    mariadb:
        image: mariadb:10.6.4-focal
        command: "--default-authentication-plugin=mysql_native_password"
        volumes:
            - m223_project_mariadb:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=supersecret123
            - MYSQL_DATABASE=minitwitter
            - MYSQL_USER=minitwitter
            - MYSQL_PASSWORD=supersecret123
        ports:
            - "4200:4200"
        networks:
            - app-network
 
    nodejs:
        image: node:22
        command: bash -c "npm install && npm run build && npm run start"
        depends_on:
            - mariadb
        restart: always
        environment:
            - DB_NAME=minitwitter
            - DB_HOST=mariadb
            - DB_USER=minitwitter
            - DB_PASSWORD=supersecret123
            - JWT_SECRET=6yVPJ0Z9MgRm8eXH7qRCOLWdN4tvOYB3+k1FiqW0dN6CKsYXu1oZQxKrREsJABWZ0AYph2rQH
            - PORT=8080
        ports:
            - "8080:8080"
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mariadb
        restart: always
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=supersecret123
        ports:
            - "9300:80"
        networks:
            - app-network
 
volumes:
    m223_project_mariadb:
 
networks:
    app-network:
        driver: bridge