const USER_TABLE = `
CREATE TABLE IF NOT EXISTS User (
    userID INT AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role ENUM('admin', 'user', 'moderator') NOT NULL
);
`;

const POST_TABLE = `
CREATE TABLE IF NOT EXISTS Post (
    postID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES User(userID) ON DELETE CASCADE
);
`;

const COMMENT_TABLE = `
CREATE TABLE IF NOT EXISTS Comment (
    commentID INT AUTO_INCREMENT PRIMARY KEY,
    postID INT NOT NULL,
    userID INT NOT NULL,
    text TEXT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (postID) REFERENCES Post(postID) ON DELETE CASCADE,
    FOREIGN KEY (userID) REFERENCES User(userID) ON DELETE CASCADE
);
`;

const LIKE_TABLE = `
CREATE TABLE IF NOT EXISTS Likes (
    postID INT NOT NULL,
    userID INT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (postID, userID),
    FOREIGN KEY (postID) REFERENCES Post(postID) ON DELETE CASCADE,
    FOREIGN KEY (userID) REFERENCES User(userID) ON DELETE CASCADE
);
`;

const NOTIFICATION_TABLE = `
CREATE TABLE IF NOT EXISTS Notification (
    notificationID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    text TEXT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    status ENUM('unread', 'read') NOT NULL,
    FOREIGN KEY (userID) REFERENCES User(userID) ON DELETE CASCADE
);
`;

export { USER_TABLE, POST_TABLE, COMMENT_TABLE, LIKE_TABLE, NOTIFICATION_TABLE };